[package]
name = "devhub_types"
version = "0.1.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "devhub_types"
crate-type = ["cdylib", "rlib"]

[dependencies]
essence_payloads = {path = "../essence_payloads"}
hc_entities = {path = "../hc_entities"}
hdk = "0.0.100"
serde = "1.0"

[dev-dependencies]
rand = "0.8.3"
serde_json = "1.0"
thiserror = "1.0"
