[package]
name = "devhub_types"
version = "0.1.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "devhub_types"
crate-type = ["cdylib", "rlib"]

[dependencies]
essence_payloads = {path = "../essence_payloads"}
flate2 = "1.0"
hc_entities = {path = "../hc_entities"}
hc_dna_utils = {path = "../dna_utils"}
hdk = "0.0.106"
rmp-serde = "0.15.5"
serde = "1.0"
serde_yaml = "0.8.17"
thiserror = "1.0"

[dev-dependencies]
rand = "0.8.3"
serde_json = "1.0"
