[package]
name = "dna_hub"
version = "0.0.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "dna_hub"
crate-type = ["cdylib", "rlib"]

[dependencies]
dna_hub_scoped_types = { path = "../../dnas/dna_hub/scoped_types" }
