[package]
name = "web_assets"
version = "0.1.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "web_assets"
crate-type = ["cdylib", "rlib"]

[dependencies]
devhub_types = {path = "../../devhub_types"}
web_assets_core = {path = "../web_assets_core"}
hc_crud_ceps = "0.53.0"
# hc_crud_ceps = {path = "../../../rust-hc-crud-ceps"}
mere_memory_types = "0.45.0"
# mere_memory_types = { path = "../../../zome-mere-memory/mere_memory_types" }
hdk = "0.0.145"
serde = "1"
serde_yaml = "0.8.17"
thiserror = "1"

[dev-dependencies]
rand = "0.8.3"
