[package]
name = "web_assets"
version = "0.1.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "web_assets"
crate-type = ["cdylib", "rlib"]

[dependencies]
devhub_types = {path = "../../devhub_types"}
hc_entities = {path = "../../hc_entities"}
hc_dna_utils = {path = "../../dna_utils"}
hdk = "0.0.100"
serde = "1.0"
serde_derive = "1.0"
thiserror = "1.0"

[dev-dependencies]
rand = "0.8.3"
