[package]
name = "web_assets"
version = "0.1.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "web_assets"
crate-type = ["cdylib", "rlib"]

[dependencies]
devhub_types = {path = "../../devhub_types"}
hc_crud_ceps = "0.1"
hdk = "0.0.106"
serde = "1"
thiserror = "1"

[dev-dependencies]
rand = "0.8.3"
