[workspace]
members = [
  "dnas/zomehub/types",
  "dnas/zomehub/sdk",
  "dnas/dnahub/types",
  "dnas/dnahub/sdk",
  "dnas/apphub/types",
  "dnas/apphub/sdk",
  "zomes/*",
]
resolver = "2"

[workspace.dependencies]
hc_coop_content_types = { git = "https://github.com/holochain/hc-cooperative-content.git", package = "hc_coop_content_types" }
hc_coop_content_sdk = { git = "https://github.com/holochain/hc-cooperative-content.git", package = "hc_coop_content_sdk" }
hc_crud_caps = "0.19"
hc_portal_sdk = { git = "https://github.com/holochain/portal-dna.git", package = "hc_portal_sdk", branch = "holochain-0.4.1" }
hc_zomehub_types = { version = "0.1", path = "dnas/zomehub/types" }
hc_zomehub_sdk = { version = "0.1", path = "dnas/zomehub/sdk" }
hdi = "=0.5.1"
hdk = "=0.4.1"
lazy_static = "1.4"
serde = "1"
zomehub = { path = "zomes/zomehub" }
