[package]
name = "apphub_types"
version = "0.0.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "apphub_types"
crate-type = ["cdylib", "rlib"]

[dependencies]
holochain_zome_types = { version = "0.2.2", features = [ "properties" ] }
mere_memory_types = "0.91.0"
rmpv = { version = "1.0.0", features = ["with-serde"] }
serde = "1"
whi_hdi_extensions = "0.4"
