[package]
name = "dna_hub_csr"
version = "0.0.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "dna_hub_csr"
crate-type = ["cdylib", "rlib"]

[dependencies]
hc_devhub_sdk = { path = "../../devhub_sdk" }
serde = "1"
dna_hub = { path = "../dna_hub" }
