[package]
name = "storage"
version = "0.1.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "storage"
crate-type = ["cdylib", "rlib"]

[dependencies]
hc_dna_reply_types = {path = "../../../../dna_reply_types"}
hc_dna_utils = {path = "../../../../dna_utils"}
hdk = "0.0.100"
serde = "1.0"
serde_derive = "1.0"
thiserror = "1.0"

[dev-dependencies]
rand = "0.8.3"
