[package]
name = "app_hub"
version = "0.0.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "app_hub"
crate-type = ["cdylib", "rlib"]

[dependencies]
app_hub_scoped_types = { path = "../../dnas/app_hub/scoped_types" }
