[package]
name = "hc_dna_reply_types"
version = "0.1.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "hc_dna_reply_types"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = "0.0.100"
serde = "1.0"
