[package]
name = "reviews"
version = "0.1.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "reviews"
crate-type = ["cdylib", "rlib"]

[dependencies]
devhub_types = {path = "../../devhub_types"}
dnarepo_core = {path = "../dnarepo_core"}
hc_crud_ceps = "0.50.1"
# hc_crud_ceps = {path = "../../../rust-hc-crud-ceps"}
mere_memory_types = "0.42.1"
# mere_memory_types = { path = "../../../zome-mere-memory/mere_memory_type" }
hdk = "0.0.142"
serde = "1"
serde_yaml = "0.8.17"
thiserror = "1"

[dev-dependencies]
rand = "0.8.3"
