[package]
name = "hc_dna_utils"
version = "0.1.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "hc_dna_utils"
crate-type = ["cdylib", "rlib"]

[dependencies]
hc_dna_reply_types = {path = "../dna_reply_types"}
hdk = "0.0.100"
thiserror = "1.0"
