[package]
name = "hc_dna_utils"
version = "0.1.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "hc_dna_utils"
crate-type = ["cdylib", "rlib"]

[dependencies]
hc_entities = {path = "../hc_entities"}
hdk = "0.0.106"
thiserror = "1.0"
