[package]
name = "zomehub"
version = "0.0.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "zomehub"
crate-type = ["cdylib", "rlib"]

[dependencies]
hc_crud_caps = "0.13"
hc_zomehub_types = { path = "../../dnas/zomehub/types" }
serde = "1"
