[package]
name = "zomehub"
version = "0.0.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "zomehub"
crate-type = ["cdylib", "rlib"]

[dependencies]
zomehub_scoped_types = { path = "../../dnas/zomehub/scoped_types" }
