[package]
name = "happ_library"
version = "0.1.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "happ_library"
crate-type = ["cdylib", "rlib"]

[dependencies]
devhub_types = {path = "../../devhub_types"}
hc_crud_ceps = "0.6.1" # = {path = "../../../rust-hc-crud-ceps"}
hdk = "0.0.109"
hex = "0"
serde = "1"
thiserror = "1"

[dev-dependencies]
rand = "0.8.3"
