[package]
name = "hc_zomehub_sdk"
version = "0.1.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "zomehub_sdk"
crate-type = ["cdylib", "rlib"]

[dependencies]
hc_devhub_sdk = { path = "../../../devhub_sdk" }
hc_zomehub_types = { path = "../types" }
serde = "1"
