[package]
name = "hc_zomehub_sdk"
version = "0.1.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"
license = "CAL-1.0"
repository = "https://github.com/holochain/devhub-dnas"
description = "SDK for the ZomeHub DNA Zomes"
readme = "README.md"

[lib]
name = "zomehub_sdk"
crate-type = ["cdylib", "rlib"]

[dependencies]
hc_devhub_sdk = { version = "0.1", path = "../../../devhub_sdk" }
hc_zomehub_types = { version = "0.1", path = "../types" }
serde = "1"
