[package]
name = "zome_hub_types"
version = "0.0.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "zome_hub_types"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdi = "=0.3.1"
mere_memory_types = "=0.88.1"
rmpv = { version = "=1.0.0", features = ["with-serde"] }
serde = "1"
whi_hdi_extensions = "=0.2.1"
