[package]
name = "apphub"
version = "0.0.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "apphub"
crate-type = ["cdylib", "rlib"]

[dependencies]
hc_apphub_types = { path = "../../dnas/apphub/types" }
hc_crud_caps = "0.10.3"
serde = "1"
